// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v4.25.1
// source: app.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Network } from "./models";

export const protobufPackage = "hydra_app";

export interface GetNetworksRequest {
}

export interface GetNetworksResponse {
  networks: Network[];
}

export interface GetPublicKeyRequest {
}

export interface GetPublicKeyResponse {
  publicKey: Uint8Array;
}

function createBaseGetNetworksRequest(): GetNetworksRequest {
  return {};
}

export const GetNetworksRequest: MessageFns<GetNetworksRequest> = {
  encode(_: GetNetworksRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetNetworksRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetNetworksRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetNetworksRequest {
    return {};
  },

  toJSON(_: GetNetworksRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetNetworksRequest>, I>>(base?: I): GetNetworksRequest {
    return GetNetworksRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetNetworksRequest>, I>>(_: I): GetNetworksRequest {
    const message = createBaseGetNetworksRequest();
    return message;
  },
};

function createBaseGetNetworksResponse(): GetNetworksResponse {
  return { networks: [] };
}

export const GetNetworksResponse: MessageFns<GetNetworksResponse> = {
  encode(message: GetNetworksResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.networks) {
      Network.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetNetworksResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetNetworksResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.networks.push(Network.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetNetworksResponse {
    return {
      networks: globalThis.Array.isArray(object?.networks) ? object.networks.map((e: any) => Network.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetNetworksResponse): unknown {
    const obj: any = {};
    if (message.networks?.length) {
      obj.networks = message.networks.map((e) => Network.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetNetworksResponse>, I>>(base?: I): GetNetworksResponse {
    return GetNetworksResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetNetworksResponse>, I>>(object: I): GetNetworksResponse {
    const message = createBaseGetNetworksResponse();
    message.networks = object.networks?.map((e) => Network.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetPublicKeyRequest(): GetPublicKeyRequest {
  return {};
}

export const GetPublicKeyRequest: MessageFns<GetPublicKeyRequest> = {
  encode(_: GetPublicKeyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPublicKeyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPublicKeyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetPublicKeyRequest {
    return {};
  },

  toJSON(_: GetPublicKeyRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPublicKeyRequest>, I>>(base?: I): GetPublicKeyRequest {
    return GetPublicKeyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPublicKeyRequest>, I>>(_: I): GetPublicKeyRequest {
    const message = createBaseGetPublicKeyRequest();
    return message;
  },
};

function createBaseGetPublicKeyResponse(): GetPublicKeyResponse {
  return { publicKey: new Uint8Array(0) };
}

export const GetPublicKeyResponse: MessageFns<GetPublicKeyResponse> = {
  encode(message: GetPublicKeyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.publicKey.length !== 0) {
      writer.uint32(10).bytes(message.publicKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPublicKeyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPublicKeyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.publicKey = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPublicKeyResponse {
    return { publicKey: isSet(object.publicKey) ? bytesFromBase64(object.publicKey) : new Uint8Array(0) };
  },

  toJSON(message: GetPublicKeyResponse): unknown {
    const obj: any = {};
    if (message.publicKey.length !== 0) {
      obj.publicKey = base64FromBytes(message.publicKey);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPublicKeyResponse>, I>>(base?: I): GetPublicKeyResponse {
    return GetPublicKeyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPublicKeyResponse>, I>>(object: I): GetPublicKeyResponse {
    const message = createBaseGetPublicKeyResponse();
    message.publicKey = object.publicKey ?? new Uint8Array(0);
    return message;
  },
};

/** General application service definition. */
export interface AppService {
  /** Get the list of active networks in the application. */
  GetNetworks(request: GetNetworksRequest): Promise<GetNetworksResponse>;
  /** Get the public key of the running application instance. */
  GetPublicKey(request: GetPublicKeyRequest): Promise<GetPublicKeyResponse>;
}

export const AppServiceServiceName = "hydra_app.AppService";
export class AppServiceClientImpl implements AppService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || AppServiceServiceName;
    this.rpc = rpc;
    this.GetNetworks = this.GetNetworks.bind(this);
    this.GetPublicKey = this.GetPublicKey.bind(this);
  }
  GetNetworks(request: GetNetworksRequest): Promise<GetNetworksResponse> {
    const data = GetNetworksRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetNetworks", data);
    return promise.then((data) => GetNetworksResponse.decode(new BinaryReader(data)));
  }

  GetPublicKey(request: GetPublicKeyRequest): Promise<GetPublicKeyResponse> {
    const data = GetPublicKeyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetPublicKey", data);
    return promise.then((data) => GetPublicKeyResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
