// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v4.25.1
// source: blockchain.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Allowance, BlockHeader, FeeEstimate, Network } from "./models";

export const protobufPackage = "hydra_app";

export interface GetBlockNumberRequest {
  network?: Network | undefined;
}

export interface GetBlockNumberResponse {
  blockNumber: string;
}

export interface GetBlockHeaderRequest {
  network?: Network | undefined;
  blockNumber: string;
}

export interface GetBlockHeaderResponse {
  blockHeader?: BlockHeader | undefined;
}

export interface GetFeeEstimatesRequest {
  network?: Network | undefined;
}

export interface GetFeeEstimatesResponse {
  feeEstimate?: FeeEstimate | undefined;
}

export interface GetTokenAllowanceRequest {
  network?: Network | undefined;
  tokenId: string;
  owner: string;
  spender: string;
}

export interface GetTokenAllowanceResponse {
  allowance?: Allowance | undefined;
}

function createBaseGetBlockNumberRequest(): GetBlockNumberRequest {
  return { network: undefined };
}

export const GetBlockNumberRequest: MessageFns<GetBlockNumberRequest> = {
  encode(message: GetBlockNumberRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.network !== undefined) {
      Network.encode(message.network, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBlockNumberRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBlockNumberRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.network = Network.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBlockNumberRequest {
    return { network: isSet(object.network) ? Network.fromJSON(object.network) : undefined };
  },

  toJSON(message: GetBlockNumberRequest): unknown {
    const obj: any = {};
    if (message.network !== undefined) {
      obj.network = Network.toJSON(message.network);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBlockNumberRequest>, I>>(base?: I): GetBlockNumberRequest {
    return GetBlockNumberRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBlockNumberRequest>, I>>(object: I): GetBlockNumberRequest {
    const message = createBaseGetBlockNumberRequest();
    message.network = (object.network !== undefined && object.network !== null)
      ? Network.fromPartial(object.network)
      : undefined;
    return message;
  },
};

function createBaseGetBlockNumberResponse(): GetBlockNumberResponse {
  return { blockNumber: "0" };
}

export const GetBlockNumberResponse: MessageFns<GetBlockNumberResponse> = {
  encode(message: GetBlockNumberResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.blockNumber !== "0") {
      writer.uint32(8).uint64(message.blockNumber);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBlockNumberResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBlockNumberResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.blockNumber = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBlockNumberResponse {
    return { blockNumber: isSet(object.blockNumber) ? globalThis.String(object.blockNumber) : "0" };
  },

  toJSON(message: GetBlockNumberResponse): unknown {
    const obj: any = {};
    if (message.blockNumber !== "0") {
      obj.blockNumber = message.blockNumber;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBlockNumberResponse>, I>>(base?: I): GetBlockNumberResponse {
    return GetBlockNumberResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBlockNumberResponse>, I>>(object: I): GetBlockNumberResponse {
    const message = createBaseGetBlockNumberResponse();
    message.blockNumber = object.blockNumber ?? "0";
    return message;
  },
};

function createBaseGetBlockHeaderRequest(): GetBlockHeaderRequest {
  return { network: undefined, blockNumber: "0" };
}

export const GetBlockHeaderRequest: MessageFns<GetBlockHeaderRequest> = {
  encode(message: GetBlockHeaderRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.network !== undefined) {
      Network.encode(message.network, writer.uint32(10).fork()).join();
    }
    if (message.blockNumber !== "0") {
      writer.uint32(16).uint64(message.blockNumber);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBlockHeaderRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBlockHeaderRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.network = Network.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.blockNumber = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBlockHeaderRequest {
    return {
      network: isSet(object.network) ? Network.fromJSON(object.network) : undefined,
      blockNumber: isSet(object.blockNumber) ? globalThis.String(object.blockNumber) : "0",
    };
  },

  toJSON(message: GetBlockHeaderRequest): unknown {
    const obj: any = {};
    if (message.network !== undefined) {
      obj.network = Network.toJSON(message.network);
    }
    if (message.blockNumber !== "0") {
      obj.blockNumber = message.blockNumber;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBlockHeaderRequest>, I>>(base?: I): GetBlockHeaderRequest {
    return GetBlockHeaderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBlockHeaderRequest>, I>>(object: I): GetBlockHeaderRequest {
    const message = createBaseGetBlockHeaderRequest();
    message.network = (object.network !== undefined && object.network !== null)
      ? Network.fromPartial(object.network)
      : undefined;
    message.blockNumber = object.blockNumber ?? "0";
    return message;
  },
};

function createBaseGetBlockHeaderResponse(): GetBlockHeaderResponse {
  return { blockHeader: undefined };
}

export const GetBlockHeaderResponse: MessageFns<GetBlockHeaderResponse> = {
  encode(message: GetBlockHeaderResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.blockHeader !== undefined) {
      BlockHeader.encode(message.blockHeader, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBlockHeaderResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBlockHeaderResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.blockHeader = BlockHeader.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBlockHeaderResponse {
    return { blockHeader: isSet(object.blockHeader) ? BlockHeader.fromJSON(object.blockHeader) : undefined };
  },

  toJSON(message: GetBlockHeaderResponse): unknown {
    const obj: any = {};
    if (message.blockHeader !== undefined) {
      obj.blockHeader = BlockHeader.toJSON(message.blockHeader);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBlockHeaderResponse>, I>>(base?: I): GetBlockHeaderResponse {
    return GetBlockHeaderResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBlockHeaderResponse>, I>>(object: I): GetBlockHeaderResponse {
    const message = createBaseGetBlockHeaderResponse();
    message.blockHeader = (object.blockHeader !== undefined && object.blockHeader !== null)
      ? BlockHeader.fromPartial(object.blockHeader)
      : undefined;
    return message;
  },
};

function createBaseGetFeeEstimatesRequest(): GetFeeEstimatesRequest {
  return { network: undefined };
}

export const GetFeeEstimatesRequest: MessageFns<GetFeeEstimatesRequest> = {
  encode(message: GetFeeEstimatesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.network !== undefined) {
      Network.encode(message.network, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetFeeEstimatesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetFeeEstimatesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.network = Network.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetFeeEstimatesRequest {
    return { network: isSet(object.network) ? Network.fromJSON(object.network) : undefined };
  },

  toJSON(message: GetFeeEstimatesRequest): unknown {
    const obj: any = {};
    if (message.network !== undefined) {
      obj.network = Network.toJSON(message.network);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetFeeEstimatesRequest>, I>>(base?: I): GetFeeEstimatesRequest {
    return GetFeeEstimatesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetFeeEstimatesRequest>, I>>(object: I): GetFeeEstimatesRequest {
    const message = createBaseGetFeeEstimatesRequest();
    message.network = (object.network !== undefined && object.network !== null)
      ? Network.fromPartial(object.network)
      : undefined;
    return message;
  },
};

function createBaseGetFeeEstimatesResponse(): GetFeeEstimatesResponse {
  return { feeEstimate: undefined };
}

export const GetFeeEstimatesResponse: MessageFns<GetFeeEstimatesResponse> = {
  encode(message: GetFeeEstimatesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.feeEstimate !== undefined) {
      FeeEstimate.encode(message.feeEstimate, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetFeeEstimatesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetFeeEstimatesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.feeEstimate = FeeEstimate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetFeeEstimatesResponse {
    return { feeEstimate: isSet(object.feeEstimate) ? FeeEstimate.fromJSON(object.feeEstimate) : undefined };
  },

  toJSON(message: GetFeeEstimatesResponse): unknown {
    const obj: any = {};
    if (message.feeEstimate !== undefined) {
      obj.feeEstimate = FeeEstimate.toJSON(message.feeEstimate);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetFeeEstimatesResponse>, I>>(base?: I): GetFeeEstimatesResponse {
    return GetFeeEstimatesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetFeeEstimatesResponse>, I>>(object: I): GetFeeEstimatesResponse {
    const message = createBaseGetFeeEstimatesResponse();
    message.feeEstimate = (object.feeEstimate !== undefined && object.feeEstimate !== null)
      ? FeeEstimate.fromPartial(object.feeEstimate)
      : undefined;
    return message;
  },
};

function createBaseGetTokenAllowanceRequest(): GetTokenAllowanceRequest {
  return { network: undefined, tokenId: "", owner: "", spender: "" };
}

export const GetTokenAllowanceRequest: MessageFns<GetTokenAllowanceRequest> = {
  encode(message: GetTokenAllowanceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.network !== undefined) {
      Network.encode(message.network, writer.uint32(10).fork()).join();
    }
    if (message.tokenId !== "") {
      writer.uint32(18).string(message.tokenId);
    }
    if (message.owner !== "") {
      writer.uint32(26).string(message.owner);
    }
    if (message.spender !== "") {
      writer.uint32(34).string(message.spender);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTokenAllowanceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTokenAllowanceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.network = Network.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tokenId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.spender = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTokenAllowanceRequest {
    return {
      network: isSet(object.network) ? Network.fromJSON(object.network) : undefined,
      tokenId: isSet(object.tokenId) ? globalThis.String(object.tokenId) : "",
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
      spender: isSet(object.spender) ? globalThis.String(object.spender) : "",
    };
  },

  toJSON(message: GetTokenAllowanceRequest): unknown {
    const obj: any = {};
    if (message.network !== undefined) {
      obj.network = Network.toJSON(message.network);
    }
    if (message.tokenId !== "") {
      obj.tokenId = message.tokenId;
    }
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    if (message.spender !== "") {
      obj.spender = message.spender;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTokenAllowanceRequest>, I>>(base?: I): GetTokenAllowanceRequest {
    return GetTokenAllowanceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTokenAllowanceRequest>, I>>(object: I): GetTokenAllowanceRequest {
    const message = createBaseGetTokenAllowanceRequest();
    message.network = (object.network !== undefined && object.network !== null)
      ? Network.fromPartial(object.network)
      : undefined;
    message.tokenId = object.tokenId ?? "";
    message.owner = object.owner ?? "";
    message.spender = object.spender ?? "";
    return message;
  },
};

function createBaseGetTokenAllowanceResponse(): GetTokenAllowanceResponse {
  return { allowance: undefined };
}

export const GetTokenAllowanceResponse: MessageFns<GetTokenAllowanceResponse> = {
  encode(message: GetTokenAllowanceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.allowance !== undefined) {
      Allowance.encode(message.allowance, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTokenAllowanceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTokenAllowanceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.allowance = Allowance.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTokenAllowanceResponse {
    return { allowance: isSet(object.allowance) ? Allowance.fromJSON(object.allowance) : undefined };
  },

  toJSON(message: GetTokenAllowanceResponse): unknown {
    const obj: any = {};
    if (message.allowance !== undefined) {
      obj.allowance = Allowance.toJSON(message.allowance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTokenAllowanceResponse>, I>>(base?: I): GetTokenAllowanceResponse {
    return GetTokenAllowanceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTokenAllowanceResponse>, I>>(object: I): GetTokenAllowanceResponse {
    const message = createBaseGetTokenAllowanceResponse();
    message.allowance = (object.allowance !== undefined && object.allowance !== null)
      ? Allowance.fromPartial(object.allowance)
      : undefined;
    return message;
  },
};

/**
 * Service definition for blockchain operations.
 * This service provides methods to interact with blockchain networks.
 */
export interface BlockchainService {
  /** Get the current block number for a specific network. */
  GetBlockNumber(request: GetBlockNumberRequest): Promise<GetBlockNumberResponse>;
  /** Get the block header for a specific block number on a network. */
  GetBlockHeader(request: GetBlockHeaderRequest): Promise<GetBlockHeaderResponse>;
  /**
   * Get fee estimates for transactions on a specific network.
   * This is useful for determining transaction costs and creating
   * efficient transactions based on current network conditions.
   */
  GetFeeEstimates(request: GetFeeEstimatesRequest): Promise<GetFeeEstimatesResponse>;
  /**
   * Get the token allowance for a specific token on a network.
   * This is useful for checking how much of a token an owner has allowed
   * a spender to use.
   */
  GetTokenAllowance(request: GetTokenAllowanceRequest): Promise<GetTokenAllowanceResponse>;
}

export const BlockchainServiceServiceName = "hydra_app.BlockchainService";
export class BlockchainServiceClientImpl implements BlockchainService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || BlockchainServiceServiceName;
    this.rpc = rpc;
    this.GetBlockNumber = this.GetBlockNumber.bind(this);
    this.GetBlockHeader = this.GetBlockHeader.bind(this);
    this.GetFeeEstimates = this.GetFeeEstimates.bind(this);
    this.GetTokenAllowance = this.GetTokenAllowance.bind(this);
  }
  GetBlockNumber(request: GetBlockNumberRequest): Promise<GetBlockNumberResponse> {
    const data = GetBlockNumberRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetBlockNumber", data);
    return promise.then((data) => GetBlockNumberResponse.decode(new BinaryReader(data)));
  }

  GetBlockHeader(request: GetBlockHeaderRequest): Promise<GetBlockHeaderResponse> {
    const data = GetBlockHeaderRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetBlockHeader", data);
    return promise.then((data) => GetBlockHeaderResponse.decode(new BinaryReader(data)));
  }

  GetFeeEstimates(request: GetFeeEstimatesRequest): Promise<GetFeeEstimatesResponse> {
    const data = GetFeeEstimatesRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetFeeEstimates", data);
    return promise.then((data) => GetFeeEstimatesResponse.decode(new BinaryReader(data)));
  }

  GetTokenAllowance(request: GetTokenAllowanceRequest): Promise<GetTokenAllowanceResponse> {
    const data = GetTokenAllowanceRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetTokenAllowance", data);
    return promise.then((data) => GetTokenAllowanceResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
