// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v4.25.1
// source: client.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { FeeOption, Network, SendAmount, SetAllowance } from "./models";

export const protobufPackage = "hydra_app";

export interface GetDepositAddressRequest {
  network?: Network | undefined;
}

export interface GetDepositAddressResponse {
  address: string;
}

export interface SendTransactionRequest {
  network?: Network | undefined;
  toAddress: string;
  amount?: SendAmount | undefined;
  feeOption?: FeeOption | undefined;
}

export interface SendTransactionResponse {
  txid: string;
}

export interface BumpTransactionResponse {
  txid: string;
}

export interface BumpTransactionRequest {
  network?: Network | undefined;
  txid: string;
  feeOption?: FeeOption | undefined;
}

export interface SendTokenTransactionRequest {
  network?: Network | undefined;
  toAddress: string;
  tokenId: string;
  amount?: SendAmount | undefined;
  feeOption?: FeeOption | undefined;
}

export interface SendTokenTransactionResponse {
  txid: string;
}

export interface SetTokenAllowanceRequest {
  network?: Network | undefined;
  spender: string;
  allowance?: SetAllowance | undefined;
  feeOption?: FeeOption | undefined;
}

export interface SetTokenAllowanceResponse {
  txid: string;
}

function createBaseGetDepositAddressRequest(): GetDepositAddressRequest {
  return { network: undefined };
}

export const GetDepositAddressRequest: MessageFns<GetDepositAddressRequest> = {
  encode(message: GetDepositAddressRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.network !== undefined) {
      Network.encode(message.network, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetDepositAddressRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDepositAddressRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.network = Network.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetDepositAddressRequest {
    return { network: isSet(object.network) ? Network.fromJSON(object.network) : undefined };
  },

  toJSON(message: GetDepositAddressRequest): unknown {
    const obj: any = {};
    if (message.network !== undefined) {
      obj.network = Network.toJSON(message.network);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetDepositAddressRequest>, I>>(base?: I): GetDepositAddressRequest {
    return GetDepositAddressRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetDepositAddressRequest>, I>>(object: I): GetDepositAddressRequest {
    const message = createBaseGetDepositAddressRequest();
    message.network = (object.network !== undefined && object.network !== null)
      ? Network.fromPartial(object.network)
      : undefined;
    return message;
  },
};

function createBaseGetDepositAddressResponse(): GetDepositAddressResponse {
  return { address: "" };
}

export const GetDepositAddressResponse: MessageFns<GetDepositAddressResponse> = {
  encode(message: GetDepositAddressResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetDepositAddressResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDepositAddressResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetDepositAddressResponse {
    return { address: isSet(object.address) ? globalThis.String(object.address) : "" };
  },

  toJSON(message: GetDepositAddressResponse): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetDepositAddressResponse>, I>>(base?: I): GetDepositAddressResponse {
    return GetDepositAddressResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetDepositAddressResponse>, I>>(object: I): GetDepositAddressResponse {
    const message = createBaseGetDepositAddressResponse();
    message.address = object.address ?? "";
    return message;
  },
};

function createBaseSendTransactionRequest(): SendTransactionRequest {
  return { network: undefined, toAddress: "", amount: undefined, feeOption: undefined };
}

export const SendTransactionRequest: MessageFns<SendTransactionRequest> = {
  encode(message: SendTransactionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.network !== undefined) {
      Network.encode(message.network, writer.uint32(10).fork()).join();
    }
    if (message.toAddress !== "") {
      writer.uint32(18).string(message.toAddress);
    }
    if (message.amount !== undefined) {
      SendAmount.encode(message.amount, writer.uint32(26).fork()).join();
    }
    if (message.feeOption !== undefined) {
      FeeOption.encode(message.feeOption, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendTransactionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendTransactionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.network = Network.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.toAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.amount = SendAmount.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.feeOption = FeeOption.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendTransactionRequest {
    return {
      network: isSet(object.network) ? Network.fromJSON(object.network) : undefined,
      toAddress: isSet(object.toAddress) ? globalThis.String(object.toAddress) : "",
      amount: isSet(object.amount) ? SendAmount.fromJSON(object.amount) : undefined,
      feeOption: isSet(object.feeOption) ? FeeOption.fromJSON(object.feeOption) : undefined,
    };
  },

  toJSON(message: SendTransactionRequest): unknown {
    const obj: any = {};
    if (message.network !== undefined) {
      obj.network = Network.toJSON(message.network);
    }
    if (message.toAddress !== "") {
      obj.toAddress = message.toAddress;
    }
    if (message.amount !== undefined) {
      obj.amount = SendAmount.toJSON(message.amount);
    }
    if (message.feeOption !== undefined) {
      obj.feeOption = FeeOption.toJSON(message.feeOption);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendTransactionRequest>, I>>(base?: I): SendTransactionRequest {
    return SendTransactionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendTransactionRequest>, I>>(object: I): SendTransactionRequest {
    const message = createBaseSendTransactionRequest();
    message.network = (object.network !== undefined && object.network !== null)
      ? Network.fromPartial(object.network)
      : undefined;
    message.toAddress = object.toAddress ?? "";
    message.amount = (object.amount !== undefined && object.amount !== null)
      ? SendAmount.fromPartial(object.amount)
      : undefined;
    message.feeOption = (object.feeOption !== undefined && object.feeOption !== null)
      ? FeeOption.fromPartial(object.feeOption)
      : undefined;
    return message;
  },
};

function createBaseSendTransactionResponse(): SendTransactionResponse {
  return { txid: "" };
}

export const SendTransactionResponse: MessageFns<SendTransactionResponse> = {
  encode(message: SendTransactionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.txid !== "") {
      writer.uint32(10).string(message.txid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendTransactionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendTransactionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.txid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendTransactionResponse {
    return { txid: isSet(object.txid) ? globalThis.String(object.txid) : "" };
  },

  toJSON(message: SendTransactionResponse): unknown {
    const obj: any = {};
    if (message.txid !== "") {
      obj.txid = message.txid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendTransactionResponse>, I>>(base?: I): SendTransactionResponse {
    return SendTransactionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendTransactionResponse>, I>>(object: I): SendTransactionResponse {
    const message = createBaseSendTransactionResponse();
    message.txid = object.txid ?? "";
    return message;
  },
};

function createBaseBumpTransactionResponse(): BumpTransactionResponse {
  return { txid: "" };
}

export const BumpTransactionResponse: MessageFns<BumpTransactionResponse> = {
  encode(message: BumpTransactionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.txid !== "") {
      writer.uint32(10).string(message.txid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BumpTransactionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBumpTransactionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.txid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BumpTransactionResponse {
    return { txid: isSet(object.txid) ? globalThis.String(object.txid) : "" };
  },

  toJSON(message: BumpTransactionResponse): unknown {
    const obj: any = {};
    if (message.txid !== "") {
      obj.txid = message.txid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BumpTransactionResponse>, I>>(base?: I): BumpTransactionResponse {
    return BumpTransactionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BumpTransactionResponse>, I>>(object: I): BumpTransactionResponse {
    const message = createBaseBumpTransactionResponse();
    message.txid = object.txid ?? "";
    return message;
  },
};

function createBaseBumpTransactionRequest(): BumpTransactionRequest {
  return { network: undefined, txid: "", feeOption: undefined };
}

export const BumpTransactionRequest: MessageFns<BumpTransactionRequest> = {
  encode(message: BumpTransactionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.network !== undefined) {
      Network.encode(message.network, writer.uint32(10).fork()).join();
    }
    if (message.txid !== "") {
      writer.uint32(18).string(message.txid);
    }
    if (message.feeOption !== undefined) {
      FeeOption.encode(message.feeOption, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BumpTransactionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBumpTransactionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.network = Network.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.txid = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.feeOption = FeeOption.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BumpTransactionRequest {
    return {
      network: isSet(object.network) ? Network.fromJSON(object.network) : undefined,
      txid: isSet(object.txid) ? globalThis.String(object.txid) : "",
      feeOption: isSet(object.feeOption) ? FeeOption.fromJSON(object.feeOption) : undefined,
    };
  },

  toJSON(message: BumpTransactionRequest): unknown {
    const obj: any = {};
    if (message.network !== undefined) {
      obj.network = Network.toJSON(message.network);
    }
    if (message.txid !== "") {
      obj.txid = message.txid;
    }
    if (message.feeOption !== undefined) {
      obj.feeOption = FeeOption.toJSON(message.feeOption);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BumpTransactionRequest>, I>>(base?: I): BumpTransactionRequest {
    return BumpTransactionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BumpTransactionRequest>, I>>(object: I): BumpTransactionRequest {
    const message = createBaseBumpTransactionRequest();
    message.network = (object.network !== undefined && object.network !== null)
      ? Network.fromPartial(object.network)
      : undefined;
    message.txid = object.txid ?? "";
    message.feeOption = (object.feeOption !== undefined && object.feeOption !== null)
      ? FeeOption.fromPartial(object.feeOption)
      : undefined;
    return message;
  },
};

function createBaseSendTokenTransactionRequest(): SendTokenTransactionRequest {
  return { network: undefined, toAddress: "", tokenId: "", amount: undefined, feeOption: undefined };
}

export const SendTokenTransactionRequest: MessageFns<SendTokenTransactionRequest> = {
  encode(message: SendTokenTransactionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.network !== undefined) {
      Network.encode(message.network, writer.uint32(10).fork()).join();
    }
    if (message.toAddress !== "") {
      writer.uint32(18).string(message.toAddress);
    }
    if (message.tokenId !== "") {
      writer.uint32(26).string(message.tokenId);
    }
    if (message.amount !== undefined) {
      SendAmount.encode(message.amount, writer.uint32(34).fork()).join();
    }
    if (message.feeOption !== undefined) {
      FeeOption.encode(message.feeOption, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendTokenTransactionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendTokenTransactionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.network = Network.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.toAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.tokenId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.amount = SendAmount.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.feeOption = FeeOption.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendTokenTransactionRequest {
    return {
      network: isSet(object.network) ? Network.fromJSON(object.network) : undefined,
      toAddress: isSet(object.toAddress) ? globalThis.String(object.toAddress) : "",
      tokenId: isSet(object.tokenId) ? globalThis.String(object.tokenId) : "",
      amount: isSet(object.amount) ? SendAmount.fromJSON(object.amount) : undefined,
      feeOption: isSet(object.feeOption) ? FeeOption.fromJSON(object.feeOption) : undefined,
    };
  },

  toJSON(message: SendTokenTransactionRequest): unknown {
    const obj: any = {};
    if (message.network !== undefined) {
      obj.network = Network.toJSON(message.network);
    }
    if (message.toAddress !== "") {
      obj.toAddress = message.toAddress;
    }
    if (message.tokenId !== "") {
      obj.tokenId = message.tokenId;
    }
    if (message.amount !== undefined) {
      obj.amount = SendAmount.toJSON(message.amount);
    }
    if (message.feeOption !== undefined) {
      obj.feeOption = FeeOption.toJSON(message.feeOption);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendTokenTransactionRequest>, I>>(base?: I): SendTokenTransactionRequest {
    return SendTokenTransactionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendTokenTransactionRequest>, I>>(object: I): SendTokenTransactionRequest {
    const message = createBaseSendTokenTransactionRequest();
    message.network = (object.network !== undefined && object.network !== null)
      ? Network.fromPartial(object.network)
      : undefined;
    message.toAddress = object.toAddress ?? "";
    message.tokenId = object.tokenId ?? "";
    message.amount = (object.amount !== undefined && object.amount !== null)
      ? SendAmount.fromPartial(object.amount)
      : undefined;
    message.feeOption = (object.feeOption !== undefined && object.feeOption !== null)
      ? FeeOption.fromPartial(object.feeOption)
      : undefined;
    return message;
  },
};

function createBaseSendTokenTransactionResponse(): SendTokenTransactionResponse {
  return { txid: "" };
}

export const SendTokenTransactionResponse: MessageFns<SendTokenTransactionResponse> = {
  encode(message: SendTokenTransactionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.txid !== "") {
      writer.uint32(10).string(message.txid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendTokenTransactionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendTokenTransactionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.txid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendTokenTransactionResponse {
    return { txid: isSet(object.txid) ? globalThis.String(object.txid) : "" };
  },

  toJSON(message: SendTokenTransactionResponse): unknown {
    const obj: any = {};
    if (message.txid !== "") {
      obj.txid = message.txid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendTokenTransactionResponse>, I>>(base?: I): SendTokenTransactionResponse {
    return SendTokenTransactionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendTokenTransactionResponse>, I>>(object: I): SendTokenTransactionResponse {
    const message = createBaseSendTokenTransactionResponse();
    message.txid = object.txid ?? "";
    return message;
  },
};

function createBaseSetTokenAllowanceRequest(): SetTokenAllowanceRequest {
  return { network: undefined, spender: "", allowance: undefined, feeOption: undefined };
}

export const SetTokenAllowanceRequest: MessageFns<SetTokenAllowanceRequest> = {
  encode(message: SetTokenAllowanceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.network !== undefined) {
      Network.encode(message.network, writer.uint32(10).fork()).join();
    }
    if (message.spender !== "") {
      writer.uint32(18).string(message.spender);
    }
    if (message.allowance !== undefined) {
      SetAllowance.encode(message.allowance, writer.uint32(26).fork()).join();
    }
    if (message.feeOption !== undefined) {
      FeeOption.encode(message.feeOption, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetTokenAllowanceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetTokenAllowanceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.network = Network.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.spender = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.allowance = SetAllowance.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.feeOption = FeeOption.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetTokenAllowanceRequest {
    return {
      network: isSet(object.network) ? Network.fromJSON(object.network) : undefined,
      spender: isSet(object.spender) ? globalThis.String(object.spender) : "",
      allowance: isSet(object.allowance) ? SetAllowance.fromJSON(object.allowance) : undefined,
      feeOption: isSet(object.feeOption) ? FeeOption.fromJSON(object.feeOption) : undefined,
    };
  },

  toJSON(message: SetTokenAllowanceRequest): unknown {
    const obj: any = {};
    if (message.network !== undefined) {
      obj.network = Network.toJSON(message.network);
    }
    if (message.spender !== "") {
      obj.spender = message.spender;
    }
    if (message.allowance !== undefined) {
      obj.allowance = SetAllowance.toJSON(message.allowance);
    }
    if (message.feeOption !== undefined) {
      obj.feeOption = FeeOption.toJSON(message.feeOption);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetTokenAllowanceRequest>, I>>(base?: I): SetTokenAllowanceRequest {
    return SetTokenAllowanceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetTokenAllowanceRequest>, I>>(object: I): SetTokenAllowanceRequest {
    const message = createBaseSetTokenAllowanceRequest();
    message.network = (object.network !== undefined && object.network !== null)
      ? Network.fromPartial(object.network)
      : undefined;
    message.spender = object.spender ?? "";
    message.allowance = (object.allowance !== undefined && object.allowance !== null)
      ? SetAllowance.fromPartial(object.allowance)
      : undefined;
    message.feeOption = (object.feeOption !== undefined && object.feeOption !== null)
      ? FeeOption.fromPartial(object.feeOption)
      : undefined;
    return message;
  },
};

function createBaseSetTokenAllowanceResponse(): SetTokenAllowanceResponse {
  return { txid: "" };
}

export const SetTokenAllowanceResponse: MessageFns<SetTokenAllowanceResponse> = {
  encode(message: SetTokenAllowanceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.txid !== "") {
      writer.uint32(10).string(message.txid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetTokenAllowanceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetTokenAllowanceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.txid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetTokenAllowanceResponse {
    return { txid: isSet(object.txid) ? globalThis.String(object.txid) : "" };
  },

  toJSON(message: SetTokenAllowanceResponse): unknown {
    const obj: any = {};
    if (message.txid !== "") {
      obj.txid = message.txid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetTokenAllowanceResponse>, I>>(base?: I): SetTokenAllowanceResponse {
    return SetTokenAllowanceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetTokenAllowanceResponse>, I>>(object: I): SetTokenAllowanceResponse {
    const message = createBaseSetTokenAllowanceResponse();
    message.txid = object.txid ?? "";
    return message;
  },
};

/** Client service definition for managing client-specific operations. */
export interface ClientService {
  /**
   * Get the deposit address for a specific network.
   * This is useful for receiving funds on the specified network.
   */
  GetDepositAddress(request: GetDepositAddressRequest): Promise<GetDepositAddressResponse>;
  /**
   * Send a transaction on a specific network.
   * This is used to transfer only the native asset of the network to another
   * address.
   * If you want to transfer a token, use the SendTokenTransaction method.
   */
  SendTransaction(request: SendTransactionRequest): Promise<SendTransactionResponse>;
  /** Bumps the fee of an existing tx */
  BumpTransaction(request: BumpTransactionRequest): Promise<BumpTransactionResponse>;
  /**
   * Send a token transaction on a specific network.
   * This is used to transfer a token from one address to another.
   * If you want to transfer the native asset of the network, use the
   * SendTransaction method.
   */
  SendTokenTransaction(request: SendTokenTransactionRequest): Promise<SendTokenTransactionResponse>;
  /**
   * Set the token allowance for a specific token on a network.
   * This is useful for allowing a spender to use a certain amount of
   * a token on behalf of the owner.
   */
  SetTokenAllowance(request: SetTokenAllowanceRequest): Promise<SetTokenAllowanceResponse>;
}

export const ClientServiceServiceName = "hydra_app.ClientService";
export class ClientServiceClientImpl implements ClientService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || ClientServiceServiceName;
    this.rpc = rpc;
    this.GetDepositAddress = this.GetDepositAddress.bind(this);
    this.SendTransaction = this.SendTransaction.bind(this);
    this.BumpTransaction = this.BumpTransaction.bind(this);
    this.SendTokenTransaction = this.SendTokenTransaction.bind(this);
    this.SetTokenAllowance = this.SetTokenAllowance.bind(this);
  }
  GetDepositAddress(request: GetDepositAddressRequest): Promise<GetDepositAddressResponse> {
    const data = GetDepositAddressRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetDepositAddress", data);
    return promise.then((data) => GetDepositAddressResponse.decode(new BinaryReader(data)));
  }

  SendTransaction(request: SendTransactionRequest): Promise<SendTransactionResponse> {
    const data = SendTransactionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "SendTransaction", data);
    return promise.then((data) => SendTransactionResponse.decode(new BinaryReader(data)));
  }

  BumpTransaction(request: BumpTransactionRequest): Promise<BumpTransactionResponse> {
    const data = BumpTransactionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "BumpTransaction", data);
    return promise.then((data) => BumpTransactionResponse.decode(new BinaryReader(data)));
  }

  SendTokenTransaction(request: SendTokenTransactionRequest): Promise<SendTokenTransactionResponse> {
    const data = SendTokenTransactionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "SendTokenTransaction", data);
    return promise.then((data) => SendTokenTransactionResponse.decode(new BinaryReader(data)));
  }

  SetTokenAllowance(request: SetTokenAllowanceRequest): Promise<SetTokenAllowanceResponse> {
    const data = SetTokenAllowanceRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "SetTokenAllowance", data);
    return promise.then((data) => SetTokenAllowanceResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
