// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v4.25.1
// source: event.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";
import { ClientEvent, Network, NodeEvent } from "./models";

export const protobufPackage = "hydra_app";

export interface SubscribeClientEventsRequest {
  network?: Network | undefined;
}

export interface SubscribeNodeEventsRequest {
  network?: Network | undefined;
}

function createBaseSubscribeClientEventsRequest(): SubscribeClientEventsRequest {
  return { network: undefined };
}

export const SubscribeClientEventsRequest: MessageFns<SubscribeClientEventsRequest> = {
  encode(message: SubscribeClientEventsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.network !== undefined) {
      Network.encode(message.network, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscribeClientEventsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscribeClientEventsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.network = Network.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubscribeClientEventsRequest {
    return { network: isSet(object.network) ? Network.fromJSON(object.network) : undefined };
  },

  toJSON(message: SubscribeClientEventsRequest): unknown {
    const obj: any = {};
    if (message.network !== undefined) {
      obj.network = Network.toJSON(message.network);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubscribeClientEventsRequest>, I>>(base?: I): SubscribeClientEventsRequest {
    return SubscribeClientEventsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubscribeClientEventsRequest>, I>>(object: I): SubscribeClientEventsRequest {
    const message = createBaseSubscribeClientEventsRequest();
    message.network = (object.network !== undefined && object.network !== null)
      ? Network.fromPartial(object.network)
      : undefined;
    return message;
  },
};

function createBaseSubscribeNodeEventsRequest(): SubscribeNodeEventsRequest {
  return { network: undefined };
}

export const SubscribeNodeEventsRequest: MessageFns<SubscribeNodeEventsRequest> = {
  encode(message: SubscribeNodeEventsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.network !== undefined) {
      Network.encode(message.network, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscribeNodeEventsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscribeNodeEventsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.network = Network.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubscribeNodeEventsRequest {
    return { network: isSet(object.network) ? Network.fromJSON(object.network) : undefined };
  },

  toJSON(message: SubscribeNodeEventsRequest): unknown {
    const obj: any = {};
    if (message.network !== undefined) {
      obj.network = Network.toJSON(message.network);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubscribeNodeEventsRequest>, I>>(base?: I): SubscribeNodeEventsRequest {
    return SubscribeNodeEventsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubscribeNodeEventsRequest>, I>>(object: I): SubscribeNodeEventsRequest {
    const message = createBaseSubscribeNodeEventsRequest();
    message.network = (object.network !== undefined && object.network !== null)
      ? Network.fromPartial(object.network)
      : undefined;
    return message;
  },
};

/** Event service definition for managing events related to clients and nodes. */
export interface EventService {
  /**
   * Subscribe to client events for a specific network.
   * This allows clients to receive real-time updates about events
   * occurring on the network, such as sync status, new blocks, transaction
   * updates, and balance changes.
   */
  SubscribeClientEvents(request: SubscribeClientEventsRequest): Observable<ClientEvent>;
  /**
   * Subscribe to node events for a specific network.
   * This allows clients to receive real-time updates about events
   * occurring on the node, such as sync status, peer connections and
   * disconnections, channel updates, and payment updates.
   */
  SubscribeNodeEvents(request: SubscribeNodeEventsRequest): Observable<NodeEvent>;
}

export const EventServiceServiceName = "hydra_app.EventService";
export class EventServiceClientImpl implements EventService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || EventServiceServiceName;
    this.rpc = rpc;
    this.SubscribeClientEvents = this.SubscribeClientEvents.bind(this);
    this.SubscribeNodeEvents = this.SubscribeNodeEvents.bind(this);
  }
  SubscribeClientEvents(request: SubscribeClientEventsRequest): Observable<ClientEvent> {
    const data = SubscribeClientEventsRequest.encode(request).finish();
    const result = this.rpc.serverStreamingRequest(this.service, "SubscribeClientEvents", data);
    return result.pipe(map((data) => ClientEvent.decode(new BinaryReader(data))));
  }

  SubscribeNodeEvents(request: SubscribeNodeEventsRequest): Observable<NodeEvent> {
    const data = SubscribeNodeEventsRequest.encode(request).finish();
    const result = this.rpc.serverStreamingRequest(this.service, "SubscribeNodeEvents", data);
    return result.pipe(map((data) => NodeEvent.decode(new BinaryReader(data))));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
  clientStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Promise<Uint8Array>;
  serverStreamingRequest(service: string, method: string, data: Uint8Array): Observable<Uint8Array>;
  bidirectionalStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Observable<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
