// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v4.25.1
// source: pricing.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { DecimalString, FiatCurrency, fiatCurrencyFromJSON, fiatCurrencyToJSON, Network } from "./models";

export const protobufPackage = "hydra_app";

export interface GetAssetFiatPriceRequest {
  network?: Network | undefined;
  assetId: string;
  fiatCurrency: FiatCurrency;
}

export interface GetAssetFiatPriceResponse {
  price?: DecimalString | undefined;
}

export interface GetAssetFiatPriceBySymbolRequest {
  assetSymbol: string;
  fiatCurrency: FiatCurrency;
}

export interface GetAssetFiatPriceBySymbolResponse {
  price?: DecimalString | undefined;
}

function createBaseGetAssetFiatPriceRequest(): GetAssetFiatPriceRequest {
  return { network: undefined, assetId: "", fiatCurrency: 0 };
}

export const GetAssetFiatPriceRequest: MessageFns<GetAssetFiatPriceRequest> = {
  encode(message: GetAssetFiatPriceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.network !== undefined) {
      Network.encode(message.network, writer.uint32(10).fork()).join();
    }
    if (message.assetId !== "") {
      writer.uint32(18).string(message.assetId);
    }
    if (message.fiatCurrency !== 0) {
      writer.uint32(24).int32(message.fiatCurrency);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAssetFiatPriceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAssetFiatPriceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.network = Network.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.assetId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.fiatCurrency = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAssetFiatPriceRequest {
    return {
      network: isSet(object.network) ? Network.fromJSON(object.network) : undefined,
      assetId: isSet(object.assetId) ? globalThis.String(object.assetId) : "",
      fiatCurrency: isSet(object.fiatCurrency) ? fiatCurrencyFromJSON(object.fiatCurrency) : 0,
    };
  },

  toJSON(message: GetAssetFiatPriceRequest): unknown {
    const obj: any = {};
    if (message.network !== undefined) {
      obj.network = Network.toJSON(message.network);
    }
    if (message.assetId !== "") {
      obj.assetId = message.assetId;
    }
    if (message.fiatCurrency !== 0) {
      obj.fiatCurrency = fiatCurrencyToJSON(message.fiatCurrency);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAssetFiatPriceRequest>, I>>(base?: I): GetAssetFiatPriceRequest {
    return GetAssetFiatPriceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAssetFiatPriceRequest>, I>>(object: I): GetAssetFiatPriceRequest {
    const message = createBaseGetAssetFiatPriceRequest();
    message.network = (object.network !== undefined && object.network !== null)
      ? Network.fromPartial(object.network)
      : undefined;
    message.assetId = object.assetId ?? "";
    message.fiatCurrency = object.fiatCurrency ?? 0;
    return message;
  },
};

function createBaseGetAssetFiatPriceResponse(): GetAssetFiatPriceResponse {
  return { price: undefined };
}

export const GetAssetFiatPriceResponse: MessageFns<GetAssetFiatPriceResponse> = {
  encode(message: GetAssetFiatPriceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.price !== undefined) {
      DecimalString.encode(message.price, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAssetFiatPriceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAssetFiatPriceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.price = DecimalString.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAssetFiatPriceResponse {
    return { price: isSet(object.price) ? DecimalString.fromJSON(object.price) : undefined };
  },

  toJSON(message: GetAssetFiatPriceResponse): unknown {
    const obj: any = {};
    if (message.price !== undefined) {
      obj.price = DecimalString.toJSON(message.price);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAssetFiatPriceResponse>, I>>(base?: I): GetAssetFiatPriceResponse {
    return GetAssetFiatPriceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAssetFiatPriceResponse>, I>>(object: I): GetAssetFiatPriceResponse {
    const message = createBaseGetAssetFiatPriceResponse();
    message.price = (object.price !== undefined && object.price !== null)
      ? DecimalString.fromPartial(object.price)
      : undefined;
    return message;
  },
};

function createBaseGetAssetFiatPriceBySymbolRequest(): GetAssetFiatPriceBySymbolRequest {
  return { assetSymbol: "", fiatCurrency: 0 };
}

export const GetAssetFiatPriceBySymbolRequest: MessageFns<GetAssetFiatPriceBySymbolRequest> = {
  encode(message: GetAssetFiatPriceBySymbolRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.assetSymbol !== "") {
      writer.uint32(10).string(message.assetSymbol);
    }
    if (message.fiatCurrency !== 0) {
      writer.uint32(16).int32(message.fiatCurrency);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAssetFiatPriceBySymbolRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAssetFiatPriceBySymbolRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.assetSymbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.fiatCurrency = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAssetFiatPriceBySymbolRequest {
    return {
      assetSymbol: isSet(object.assetSymbol) ? globalThis.String(object.assetSymbol) : "",
      fiatCurrency: isSet(object.fiatCurrency) ? fiatCurrencyFromJSON(object.fiatCurrency) : 0,
    };
  },

  toJSON(message: GetAssetFiatPriceBySymbolRequest): unknown {
    const obj: any = {};
    if (message.assetSymbol !== "") {
      obj.assetSymbol = message.assetSymbol;
    }
    if (message.fiatCurrency !== 0) {
      obj.fiatCurrency = fiatCurrencyToJSON(message.fiatCurrency);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAssetFiatPriceBySymbolRequest>, I>>(
    base?: I,
  ): GetAssetFiatPriceBySymbolRequest {
    return GetAssetFiatPriceBySymbolRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAssetFiatPriceBySymbolRequest>, I>>(
    object: I,
  ): GetAssetFiatPriceBySymbolRequest {
    const message = createBaseGetAssetFiatPriceBySymbolRequest();
    message.assetSymbol = object.assetSymbol ?? "";
    message.fiatCurrency = object.fiatCurrency ?? 0;
    return message;
  },
};

function createBaseGetAssetFiatPriceBySymbolResponse(): GetAssetFiatPriceBySymbolResponse {
  return { price: undefined };
}

export const GetAssetFiatPriceBySymbolResponse: MessageFns<GetAssetFiatPriceBySymbolResponse> = {
  encode(message: GetAssetFiatPriceBySymbolResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.price !== undefined) {
      DecimalString.encode(message.price, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAssetFiatPriceBySymbolResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAssetFiatPriceBySymbolResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.price = DecimalString.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAssetFiatPriceBySymbolResponse {
    return { price: isSet(object.price) ? DecimalString.fromJSON(object.price) : undefined };
  },

  toJSON(message: GetAssetFiatPriceBySymbolResponse): unknown {
    const obj: any = {};
    if (message.price !== undefined) {
      obj.price = DecimalString.toJSON(message.price);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAssetFiatPriceBySymbolResponse>, I>>(
    base?: I,
  ): GetAssetFiatPriceBySymbolResponse {
    return GetAssetFiatPriceBySymbolResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAssetFiatPriceBySymbolResponse>, I>>(
    object: I,
  ): GetAssetFiatPriceBySymbolResponse {
    const message = createBaseGetAssetFiatPriceBySymbolResponse();
    message.price = (object.price !== undefined && object.price !== null)
      ? DecimalString.fromPartial(object.price)
      : undefined;
    return message;
  },
};

/** Pricing service definition for retrieving asset prices. */
export interface PricingService {
  /** Get the fiat price of a specific asset on a specific network. */
  GetAssetFiatPrice(request: GetAssetFiatPriceRequest): Promise<GetAssetFiatPriceResponse>;
  /** Get the fiat price of an asset by its symbol. */
  GetAssetFiatPriceBySymbol(request: GetAssetFiatPriceBySymbolRequest): Promise<GetAssetFiatPriceBySymbolResponse>;
}

export const PricingServiceServiceName = "hydra_app.PricingService";
export class PricingServiceClientImpl implements PricingService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || PricingServiceServiceName;
    this.rpc = rpc;
    this.GetAssetFiatPrice = this.GetAssetFiatPrice.bind(this);
    this.GetAssetFiatPriceBySymbol = this.GetAssetFiatPriceBySymbol.bind(this);
  }
  GetAssetFiatPrice(request: GetAssetFiatPriceRequest): Promise<GetAssetFiatPriceResponse> {
    const data = GetAssetFiatPriceRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetAssetFiatPrice", data);
    return promise.then((data) => GetAssetFiatPriceResponse.decode(new BinaryReader(data)));
  }

  GetAssetFiatPriceBySymbol(request: GetAssetFiatPriceBySymbolRequest): Promise<GetAssetFiatPriceBySymbolResponse> {
    const data = GetAssetFiatPriceBySymbolRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetAssetFiatPriceBySymbol", data);
    return promise.then((data) => GetAssetFiatPriceBySymbolResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
