// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v4.25.1
// source: wallet.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Balance, Network, Transaction } from "./models";

export const protobufPackage = "hydra_app";

export interface GetBalancesRequest {
  network?: Network | undefined;
}

export interface GetBalancesResponse {
  /** key: asset_id */
  balances: { [key: string]: Balance };
}

export interface GetBalancesResponse_BalancesEntry {
  key: string;
  value?: Balance | undefined;
}

export interface GetBalanceRequest {
  network?: Network | undefined;
  assetId: string;
}

export interface GetBalanceResponse {
  /** onchain and offchain balances for the specified asset */
  balance?: Balance | undefined;
}

export interface GetTransactionsRequest {
  network?: Network | undefined;
}

export interface GetTransactionsResponse {
  transactions: Transaction[];
}

export interface GetTransactionRequest {
  network?: Network | undefined;
  txid: string;
}

export interface GetTransactionResponse {
  transaction?: Transaction | undefined;
}

function createBaseGetBalancesRequest(): GetBalancesRequest {
  return { network: undefined };
}

export const GetBalancesRequest: MessageFns<GetBalancesRequest> = {
  encode(message: GetBalancesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.network !== undefined) {
      Network.encode(message.network, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBalancesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBalancesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.network = Network.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBalancesRequest {
    return { network: isSet(object.network) ? Network.fromJSON(object.network) : undefined };
  },

  toJSON(message: GetBalancesRequest): unknown {
    const obj: any = {};
    if (message.network !== undefined) {
      obj.network = Network.toJSON(message.network);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBalancesRequest>, I>>(base?: I): GetBalancesRequest {
    return GetBalancesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBalancesRequest>, I>>(object: I): GetBalancesRequest {
    const message = createBaseGetBalancesRequest();
    message.network = (object.network !== undefined && object.network !== null)
      ? Network.fromPartial(object.network)
      : undefined;
    return message;
  },
};

function createBaseGetBalancesResponse(): GetBalancesResponse {
  return { balances: {} };
}

export const GetBalancesResponse: MessageFns<GetBalancesResponse> = {
  encode(message: GetBalancesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    Object.entries(message.balances).forEach(([key, value]) => {
      GetBalancesResponse_BalancesEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBalancesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBalancesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = GetBalancesResponse_BalancesEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.balances[entry1.key] = entry1.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBalancesResponse {
    return {
      balances: isObject(object.balances)
        ? Object.entries(object.balances).reduce<{ [key: string]: Balance }>((acc, [key, value]) => {
          acc[key] = Balance.fromJSON(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: GetBalancesResponse): unknown {
    const obj: any = {};
    if (message.balances) {
      const entries = Object.entries(message.balances);
      if (entries.length > 0) {
        obj.balances = {};
        entries.forEach(([k, v]) => {
          obj.balances[k] = Balance.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBalancesResponse>, I>>(base?: I): GetBalancesResponse {
    return GetBalancesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBalancesResponse>, I>>(object: I): GetBalancesResponse {
    const message = createBaseGetBalancesResponse();
    message.balances = Object.entries(object.balances ?? {}).reduce<{ [key: string]: Balance }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = Balance.fromPartial(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseGetBalancesResponse_BalancesEntry(): GetBalancesResponse_BalancesEntry {
  return { key: "", value: undefined };
}

export const GetBalancesResponse_BalancesEntry: MessageFns<GetBalancesResponse_BalancesEntry> = {
  encode(message: GetBalancesResponse_BalancesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      Balance.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBalancesResponse_BalancesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBalancesResponse_BalancesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = Balance.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBalancesResponse_BalancesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? Balance.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: GetBalancesResponse_BalancesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = Balance.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBalancesResponse_BalancesEntry>, I>>(
    base?: I,
  ): GetBalancesResponse_BalancesEntry {
    return GetBalancesResponse_BalancesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBalancesResponse_BalancesEntry>, I>>(
    object: I,
  ): GetBalancesResponse_BalancesEntry {
    const message = createBaseGetBalancesResponse_BalancesEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? Balance.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseGetBalanceRequest(): GetBalanceRequest {
  return { network: undefined, assetId: "" };
}

export const GetBalanceRequest: MessageFns<GetBalanceRequest> = {
  encode(message: GetBalanceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.network !== undefined) {
      Network.encode(message.network, writer.uint32(10).fork()).join();
    }
    if (message.assetId !== "") {
      writer.uint32(18).string(message.assetId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBalanceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBalanceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.network = Network.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.assetId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBalanceRequest {
    return {
      network: isSet(object.network) ? Network.fromJSON(object.network) : undefined,
      assetId: isSet(object.assetId) ? globalThis.String(object.assetId) : "",
    };
  },

  toJSON(message: GetBalanceRequest): unknown {
    const obj: any = {};
    if (message.network !== undefined) {
      obj.network = Network.toJSON(message.network);
    }
    if (message.assetId !== "") {
      obj.assetId = message.assetId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBalanceRequest>, I>>(base?: I): GetBalanceRequest {
    return GetBalanceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBalanceRequest>, I>>(object: I): GetBalanceRequest {
    const message = createBaseGetBalanceRequest();
    message.network = (object.network !== undefined && object.network !== null)
      ? Network.fromPartial(object.network)
      : undefined;
    message.assetId = object.assetId ?? "";
    return message;
  },
};

function createBaseGetBalanceResponse(): GetBalanceResponse {
  return { balance: undefined };
}

export const GetBalanceResponse: MessageFns<GetBalanceResponse> = {
  encode(message: GetBalanceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.balance !== undefined) {
      Balance.encode(message.balance, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBalanceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBalanceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.balance = Balance.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBalanceResponse {
    return { balance: isSet(object.balance) ? Balance.fromJSON(object.balance) : undefined };
  },

  toJSON(message: GetBalanceResponse): unknown {
    const obj: any = {};
    if (message.balance !== undefined) {
      obj.balance = Balance.toJSON(message.balance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBalanceResponse>, I>>(base?: I): GetBalanceResponse {
    return GetBalanceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBalanceResponse>, I>>(object: I): GetBalanceResponse {
    const message = createBaseGetBalanceResponse();
    message.balance = (object.balance !== undefined && object.balance !== null)
      ? Balance.fromPartial(object.balance)
      : undefined;
    return message;
  },
};

function createBaseGetTransactionsRequest(): GetTransactionsRequest {
  return { network: undefined };
}

export const GetTransactionsRequest: MessageFns<GetTransactionsRequest> = {
  encode(message: GetTransactionsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.network !== undefined) {
      Network.encode(message.network, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTransactionsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTransactionsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.network = Network.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTransactionsRequest {
    return { network: isSet(object.network) ? Network.fromJSON(object.network) : undefined };
  },

  toJSON(message: GetTransactionsRequest): unknown {
    const obj: any = {};
    if (message.network !== undefined) {
      obj.network = Network.toJSON(message.network);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTransactionsRequest>, I>>(base?: I): GetTransactionsRequest {
    return GetTransactionsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTransactionsRequest>, I>>(object: I): GetTransactionsRequest {
    const message = createBaseGetTransactionsRequest();
    message.network = (object.network !== undefined && object.network !== null)
      ? Network.fromPartial(object.network)
      : undefined;
    return message;
  },
};

function createBaseGetTransactionsResponse(): GetTransactionsResponse {
  return { transactions: [] };
}

export const GetTransactionsResponse: MessageFns<GetTransactionsResponse> = {
  encode(message: GetTransactionsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.transactions) {
      Transaction.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTransactionsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTransactionsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.transactions.push(Transaction.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTransactionsResponse {
    return {
      transactions: globalThis.Array.isArray(object?.transactions)
        ? object.transactions.map((e: any) => Transaction.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetTransactionsResponse): unknown {
    const obj: any = {};
    if (message.transactions?.length) {
      obj.transactions = message.transactions.map((e) => Transaction.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTransactionsResponse>, I>>(base?: I): GetTransactionsResponse {
    return GetTransactionsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTransactionsResponse>, I>>(object: I): GetTransactionsResponse {
    const message = createBaseGetTransactionsResponse();
    message.transactions = object.transactions?.map((e) => Transaction.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetTransactionRequest(): GetTransactionRequest {
  return { network: undefined, txid: "" };
}

export const GetTransactionRequest: MessageFns<GetTransactionRequest> = {
  encode(message: GetTransactionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.network !== undefined) {
      Network.encode(message.network, writer.uint32(10).fork()).join();
    }
    if (message.txid !== "") {
      writer.uint32(18).string(message.txid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTransactionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTransactionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.network = Network.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.txid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTransactionRequest {
    return {
      network: isSet(object.network) ? Network.fromJSON(object.network) : undefined,
      txid: isSet(object.txid) ? globalThis.String(object.txid) : "",
    };
  },

  toJSON(message: GetTransactionRequest): unknown {
    const obj: any = {};
    if (message.network !== undefined) {
      obj.network = Network.toJSON(message.network);
    }
    if (message.txid !== "") {
      obj.txid = message.txid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTransactionRequest>, I>>(base?: I): GetTransactionRequest {
    return GetTransactionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTransactionRequest>, I>>(object: I): GetTransactionRequest {
    const message = createBaseGetTransactionRequest();
    message.network = (object.network !== undefined && object.network !== null)
      ? Network.fromPartial(object.network)
      : undefined;
    message.txid = object.txid ?? "";
    return message;
  },
};

function createBaseGetTransactionResponse(): GetTransactionResponse {
  return { transaction: undefined };
}

export const GetTransactionResponse: MessageFns<GetTransactionResponse> = {
  encode(message: GetTransactionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transaction !== undefined) {
      Transaction.encode(message.transaction, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTransactionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTransactionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.transaction = Transaction.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTransactionResponse {
    return { transaction: isSet(object.transaction) ? Transaction.fromJSON(object.transaction) : undefined };
  },

  toJSON(message: GetTransactionResponse): unknown {
    const obj: any = {};
    if (message.transaction !== undefined) {
      obj.transaction = Transaction.toJSON(message.transaction);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTransactionResponse>, I>>(base?: I): GetTransactionResponse {
    return GetTransactionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTransactionResponse>, I>>(object: I): GetTransactionResponse {
    const message = createBaseGetTransactionResponse();
    message.transaction = (object.transaction !== undefined && object.transaction !== null)
      ? Transaction.fromPartial(object.transaction)
      : undefined;
    return message;
  },
};

/**
 * Wallet service definition for managing wallet-related operations.
 * This service provides methods for retrieving balances and transactions
 * associated with a specific network.
 */
export interface WalletService {
  /**
   * Get the balances of assets in the wallet for a specific network.
   * This returns a map of asset IDs to their corresponding onchain and offchain
   * balances.
   */
  GetBalances(request: GetBalancesRequest): Promise<GetBalancesResponse>;
  /**
   * Get the balance of a specific asset in the wallet for a specific network.
   * This returns the onchain and offchain balances for the specified asset ID.
   */
  GetBalance(request: GetBalanceRequest): Promise<GetBalanceResponse>;
  /**
   * Get the list of transactions associated with the wallet for a specific
   * network.
   */
  GetTransactions(request: GetTransactionsRequest): Promise<GetTransactionsResponse>;
  /** Get the details of a specific transaction by its ID for a specific network. */
  GetTransaction(request: GetTransactionRequest): Promise<GetTransactionResponse>;
}

export const WalletServiceServiceName = "hydra_app.WalletService";
export class WalletServiceClientImpl implements WalletService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || WalletServiceServiceName;
    this.rpc = rpc;
    this.GetBalances = this.GetBalances.bind(this);
    this.GetBalance = this.GetBalance.bind(this);
    this.GetTransactions = this.GetTransactions.bind(this);
    this.GetTransaction = this.GetTransaction.bind(this);
  }
  GetBalances(request: GetBalancesRequest): Promise<GetBalancesResponse> {
    const data = GetBalancesRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetBalances", data);
    return promise.then((data) => GetBalancesResponse.decode(new BinaryReader(data)));
  }

  GetBalance(request: GetBalanceRequest): Promise<GetBalanceResponse> {
    const data = GetBalanceRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetBalance", data);
    return promise.then((data) => GetBalanceResponse.decode(new BinaryReader(data)));
  }

  GetTransactions(request: GetTransactionsRequest): Promise<GetTransactionsResponse> {
    const data = GetTransactionsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetTransactions", data);
    return promise.then((data) => GetTransactionsResponse.decode(new BinaryReader(data)));
  }

  GetTransaction(request: GetTransactionRequest): Promise<GetTransactionResponse> {
    const data = GetTransactionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetTransaction", data);
    return promise.then((data) => GetTransactionResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
